### ISSUE TITLE
Regular and dev mode `juliapkg.json` cause resolver to crash

### ISSUE THREAD

**Issue by ma-sadeghi** [JuliaPy/pyjuliapkg#27]
Suppose you first install `SomePackage.jl` in regular mode, then decide to install it in dev mode. `merge_unique` merges all fields of both `json` files, but in dev mode, `url` and `rev` must not be passed, or else `Pkg.add` complains.

**Comment by cjdoris** [comment]
Please post some code showing how to get the error your seeing.

**Comment by ma-sadeghi** [comment]
Never mind, I can no longer reproduce it. Likely something on my end. Thanks for the follow up though :)
