### ISSUE TITLE
Refactor identifying whether in a virtualenv

### ISSUE THREAD

**Issue by ma-sadeghi** [JuliaPy/pyjuliapkg#30]
Would you consider a PR refactoring the way to identify if in a virtualenv? Currently, it's by inspecting `VIRTUAL_ENV` environment variable, which is not reliable.

**Comment by cjdoris** [comment]
Sure. How is it not reliable? What would be better?

**Comment by cjdoris** [comment]
Ah cool, yeah a PR for that sounds good. Please include a link to the docs in a comment.

This can also resolve the ambiguity which currently causes and error if both VIRTUAL_ENV and CONDA_PREFIX are set - with this method we are sure that the virtual environment takes precedence (i.e. have created a virtual environment inside a Conda environment and not the other way around).

Just need to double check that the test doesn't pass in a Conda environment.
