### ISSUE TITLE
Consider adding a public API for dependencies

### ISSUE THREAD

**Issue by amilsted** [JuliaPy/pyjuliapkg#33]
I have code (see https://github.com/JuliaPy/pyjuliapkg/issues/20) that uses Julia to check package versions match up with juliapkg expectations. I use it with juliapkg in "offline" mode to avoid calls to `Pkg.add` where dependencies are already installed. I only switch to online mode if julia doesn't load, or if there is a version mismatch. This speeds up launch time considerably.

Assuming this code can't go into juliapkg itself (since it doesn't link in julia), it would be nice to have a public API to get the dependencies from juliapkg. Something like the current `find_requirements()`. @cjdoris Do you think we could just make that public?

I guess an alternative is to add such functionality to juliacall.

**Comment by cjdoris** [comment]
c.f. https://github.com/JuliaPy/pyjuliapkg/issues/20#issuecomment-2113196448 if you are seeing the packages being frequently reinstalled, then something is wrong

I'm not opposed to exposing more of the dependency finding functionality as API, but it sounds like you have a deeper issue.
